### ISSUE TITLE
Server Crash when load db

### ISSUE THREAD

**Issue by leewheel** [DeKaDeNcE/WoWCore#6]
I just use  the data files download from https://tc.arctium.io/master/  , but world server crashed when load db2, WorldServer.log:
`05/29/2023 19:16:54 Info: [SqlUpdates] Automatic database updates are disabled for all databases!
05/29/2023 19:16:55 Info: [ServerLoading] Realm running as realm ID 1 
05/29/2023 19:16:55 Info: [Server] Using World DB: TDB 1007.23041
05/29/2023 19:16:55 Info: [ServerLoading] Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
05/29/2023 19:16:55 Info: [ServerLoading] Client cache version set to: 0
05/29/2023 19:16:55 Info: [ServerLoading] Using enUS DBC Locale
05/29/2023 19:16:55 Info: [ServerLoading] Using DataDir Data
05/29/2023 19:16:55 Info: [ServerLoading] MMap data directory is: Data\mmaps
05/29/2023 19:16:55 Info: [ServerLoading] VMap support included. LineOfSight: True, getHeight: True, indoorCheck: True
05/29/2023 19:16:55 Info: [ServerLoading] VMap data directory is: Data\vmaps
05/29/2023 19:16:55 Info: [ServerLoading] Loading Cypher Strings...
05/29/2023 19:16:55 Info: [ServerLoading] Loaded 1042 CypherStrings in 17 ms
05/29/2023 19:16:55 Info: [ServerLoading] Initialize DataStorage...
05/29/2023 19:16:55 Error: [ServerLoading] Error loading Data/dbc/enUS/Achievement.db2.`
and Crash.log is :
`05/29/2023 19:16:55 Fatal: [Crash] UnhandledExceptionHandler in  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Game.DataStorage.DB6Storage`1.LoadFromDB(Boolean custom, HotfixStatements preparedStatement) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Game\DataStorage\ClientReader\DB6Storage.cs:line 234
   at Game.DataStorage.DB6Storage`1.LoadHotfixData(BitSet availableDb2Locales, HotfixStatements preparedStatement, HotfixStatements preparedStatementLocale) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Game\DataStorage\ClientReader\DB6Storage.cs:line 70
   at Game.DataStorage.CliDB.<LoadStores>g__ReadDB2|0_0[T](String fileName, HotfixStatements preparedStatement, HotfixStatements preparedStatementLocale, <>c__DisplayClass0_0&) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Game\DataStorage\CliDB.cs:line 38
   at Game.DataStorage.CliDB.LoadStores(String dataPath, Locale defaultLocale) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Game\DataStorage\CliDB.cs:line 45
   at Game.WorldManager.SetInitialWorldSettings() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Game\World\WorldManager.cs:line 423
   at WorldServer.Server.Main() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\WorldServer\Server.cs:line 49`

**Comment by ZaDarkSide** [comment]
Data from https://tc.arctium.io/master/ is no longer compatible with this emulator for now.

Arctium has data for newer version 10.1.0 this emulator supports only older version 10.0.7 for now.

Try https://github.com/CypherCore/CypherCore it supports version 10.1.0 that should load correctly the data from Arctium, or just wait until we update also to 10.1.0 or extract yourself data from WoW Game Client 10.0.7

**Comment by leewheel** [comment]
I  try download the 10.0.7 client.... Thanks!
