### ISSUE TITLE
worldserver crash when import sql

### ISSUE THREAD

**Issue by leewheel** [DeKaDeNcE/WoWCore#8]
today's update worldserver crash by this:
```
06/16/2023 10:49:15 Fatal: [Crash] UnhandledExceptionHandler in  Exception: System.Exception: update failed
   at Framework.Database.MySqlBase`1.ApplyFile(String path, Boolean useDatabase) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\MySqlBase.cs:line 318
   at Framework.Database.DatabaseUpdater`1.ApplyFile(String path) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\DatabaseUpdater.cs:line 260
   at Framework.Database.DatabaseUpdater`1.ApplyTimedFile(String path) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\DatabaseUpdater.cs:line 252
   at Framework.Database.DatabaseUpdater`1.Update() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\DatabaseUpdater.cs:line 195
   at Framework.Database.DatabaseLoader.<>c__DisplayClass1_0`1.<AddDatabase>b__2() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\DatabaseLoader.cs:line 73
   at Framework.Database.DatabaseLoader.Process(List`1 list) in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\DatabaseLoader.cs:line 163
   at Framework.Database.DatabaseLoader.UpdateDatabases() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\DatabaseLoader.cs:line 178
   at Framework.Database.DatabaseLoader.Load() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\Framework\Database\DatabaseLoader.cs:line 144
   at WorldServer.Server.StartDB() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\WorldServer\Server.cs:line 143
   at WorldServer.Server.Main() in C:\MyProject\1MyWoWCSharp\WoWCoreCopy\Source\WorldServer\Server.cs:line 38

```

**Comment by ZaDarkSide** [comment]
Try cloning again the repo and recompile.

**Comment by leewheel** [comment]
i'll try,thanks!

**Comment by leewheel** [comment]
It's works! great!
